In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'IMDb movies.csv'

In [ ]:
# seleccionar columnas
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# concat()

## Concatenar verticalmente

In [ ]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'F'],
                    'age': [40, 21, 19, 24]})

In [ ]:
pd.concat([df1, df2], axis=0, ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

### Ejercicio

In [ ]:
# extraer 50% de muestra del dataframe original (df_movies)
df_sample = df_movies.sample(frac=0.5)

In [ ]:
# shape
print(df_movies.shape)
print(df_sample.shape)

(85855, 5)
(42928, 5)

In [ ]:
# concatenar verticalmente df_movies y df_samples
df_concat_vertical = pd.concat([df_movies, df_sample], axis=0)

In [ ]:
df_concat_vertical.shape

(128783, 5)

## Concatenar horizontalmente

In [ ]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

In [ ]:
pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

### Ejercicio

In [ ]:
# shape de dataframes que vamos a concatenar
print(df_movies.shape)
print(df_ratings.shape)

(85855, 5)
(85855, 3)

In [ ]:
# fijar 'imdb_title_id' como index de df_ratings y df_movies
df_ratings.set_index('imdb_title_id', inplace=True)
df_movies.set_index('imdb_title_id', inplace=True)

In [ ]:
# concatenar df_movies y df_ratings usando columna 'imdb_title_id' (horizontalmente)
df_concat_horizontal = pd.concat([df_movies, df_ratings], axis=1)

In [ ]:
# shape de concatenacion
df_concat_horizontal.shape

(85855, 6)