In [1]:
import pandas as pd

In [2]:
# leer el archivos csv
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Agregar nueva columna

## assign()

¿Cuando usar assign()?
- Agregar multiples columnas en una sola linea de codigo
- Cuando se necesita sobreescribir los valores de una columna existente (buena practica)

Devuelve un nuevo objeto (copia) con todas las columnas originales ademas de las nuevas

In [3]:
import numpy as np

In [4]:
# crear numeros aleatorios para nuestra nuevas columnas "score"
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [5]:
# crear una serie usando los numeros aleatorios
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [6]:
# usando assign() para agregar multiples columnas
df_exams = df_exams.assign(score1=series1, score2=series2)

In [7]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,31,96
1,female,group C,some college,standard,completed,69,90,88,36,36
2,female,group B,master's degree,standard,none,90,95,93,84,6
3,male,group A,associate's degree,free/reduced,none,47,57,44,86,58
4,male,group C,some college,standard,none,76,78,75,90,38
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,18,8
996,male,group C,high school,free/reduced,none,62,55,55,27,56
997,female,group C,high school,free/reduced,completed,59,71,65,13,76
998,female,group D,some college,standard,completed,68,78,77,47,40
999,female,group D,some college,free/reduced,none,77,86,86,66,53

## insert()

Insertar una nueva columna en una posicion especifica o index.

In [8]:
# usar insert() para adicionar una columna en una posicion especifica
df_exams.insert(1, 'test', series1)

In [9]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,31,group B,bachelor's degree,standard,none,72,72,74,31,96
1,female,36,group C,some college,standard,completed,69,90,88,36,36
2,female,84,group B,master's degree,standard,none,90,95,93,84,6
3,male,86,group A,associate's degree,free/reduced,none,47,57,44,86,58
4,male,90,group C,some college,standard,none,76,78,75,90,38
...,...,...,...,...,...,...,...,...,...,...,...
995,female,18,group E,master's degree,standard,completed,88,99,95,18,8
996,male,27,group C,high school,free/reduced,none,62,55,55,27,56
997,female,13,group C,high school,free/reduced,completed,59,71,65,13,76
998,female,47,group D,some college,standard,completed,68,78,77,47,40
999,female,66,group D,some college,free/reduced,none,77,86,86,66,53